### ISSUE TITLE
[enhancement] Setting redsys vars

### ISSUE THREAD

**Issue by mrcmorales** [crevillo/payum-redsys-bundle#1]
Hi,

I have an application that is multi-site, and every site has different redsys config, then I need change this vars after call the api.

May be an option will be add setters to change this vars.

What do you think ? Do you accept a PR with this improve?

Thanks

**Comment by crevillo** [comment]
Sure, why not. I ping @makasim to know his opinion

**Comment by makasim** [comment]
You have to create separate instance of payment for each site, with different credentials.

**Comment by mrcmorales** [comment]
@makasim How I can do It ? 

Because when i call sf2 service, the constructor sets the vars setted in config.yml , and I nned change it

**Comment by makasim** [comment]
```
# app/config/config.yml

payum:
  payments: # or contexts on 0.13
    foo_redsys:
      redsys: 
         #options
    bar_redsys:
      redsys: 
         #options

```
